### ISSUE TITLE
Installation for Neo-Linuxite

### ISSUE THREAD

**Issue by qalisto** [bostrt/quikey#23]
Robert:

You invested a lot of time into writing this app, yet instructions or methods for easier instruction for the growing users of Linux (abandoning Windows) is not done.

Some of us can't build these apps.  Can't compile - make - etc.  

We simply want an intriguing new app to *work* without having to be a senior engineer at *Waymo*.

You would achieve far greater fame if you simply made this work into an installable Debian package.  

A GUI would make you a cult figure.  

Text replacement is critical for serious OS users and Autokey is not user-friendly.  

But alas, we cannot even get the Daemon to run.

What do we need to provide you to diagnose what is missing?

Is it obvious?

Really keen to get QK running on my MX Linux installation.

If you could assist us pitiful newbies -  be assured it would be appreciated.

Best,
Qalisto

=================================================

Here is the sequence.

INSTALLATION:

$ pip3 install --user quikey
Collecting quikey
  Downloading https://files.pythonhosted.org/packages/6c/58/ebb25a4ffd698b0f0bf196443452ebbe5d78ac04a96d3964ebac8118144b/quikey-0.1.0-py3-none-any.whl
Collecting click (from quikey)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 516kB/s 
Collecting tinydb (from quikey)
  Downloading https://files.pythonhosted.org/packages/dc/90/ced9f2a57513eb75dce70760e55967ceedbf2dc158b6a66f1bf87ac8fab0/tinydb-3.14.1-py2.py3-none-any.whl
Collecting terminaltables (from quikey)
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting pynput (from quikey)
  Downloading https://files.pythonhosted.org/packages/94/92/9e83e382f808b57330bed06855489242b77c262406aeca4960a16c8666d9/pynput-1.4.2-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 1.2MB/s 
Collecting python-daemon (from quikey)
  Downloading https://files.pythonhosted.org/packages/e6/44/6734382d1beb8704137ec94589e7d173a415f3396e34d020fb6b6271c2ff/python_daemon-2.2.3-py2.py3-none-any.whl
Collecting humanize (from quikey)
  Downloading https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting colored (from quikey)
  Downloading https://files.pythonhosted.org/packages/58/07/636616667b47d3115b0288311511c5fb446d0e499036b7db858704c89066/colored-1.3.93.tar.gz
Collecting inotify-simple (from quikey)
  Downloading https://files.pythonhosted.org/packages/55/80/4bbd33f6d6b305c509a90b37c1cf7255000344f513b36827ec2c17af5ad5/inotify_simple-1.1.8.tar.gz
Collecting xdg (from quikey)
  Downloading https://files.pythonhosted.org/packages/cc/7e/10b63c5d0546fc168ced3465c520b00de698d960e1c74800aea2a777aa8e/xdg-3.0.2-py2.py3-none-any.whl
Collecting python-xlib>=0.17; "linux" in sys_platform (from pynput->quikey)
  Downloading https://files.pythonhosted.org/packages/f7/91/9f794491d1a8b810a9d4bb8fc9766a98354cb62bd6990685032b00f87001/python_xlib-0.25-py2.py3-none-any.whl (165kB)
    100% |████████████████████████████████| 174kB 1.3MB/s 
Collecting six (from pynput->quikey)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting lockfile>=0.10 (from python-daemon->quikey)
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting setuptools (from python-daemon->quikey)
  Downloading https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl (576kB)
    100% |████████████████████████████████| 583kB 1.5MB/s 
Collecting docutils (from python-daemon->quikey)
  Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)
    100% |████████████████████████████████| 552kB 1.5MB/s 
Building wheels for collected packages: terminaltables, humanize, colored, inotify-simple
  Running setup.py bdist_wheel for terminaltables ... done
  Stored in directory: /home/bdl/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
  Running setup.py bdist_wheel for humanize ... done
  Stored in directory: /home/bdl/.cache/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44
  Running setup.py bdist_wheel for colored ... done
  Stored in directory: /home/bdl/.cache/pip/wheels/52/c3/b7/ac21460710230feb409fee89bf594c4f2660ff7b67491d128f
  Running setup.py bdist_wheel for inotify-simple ... done
  Stored in directory: /home/bdl/.cache/pip/wheels/11/5d/7e/f325d21ffec71263368df56a2af6ab3c802e0e869abd4b3c03
Successfully built terminaltables humanize colored inotify-simple
Installing collected packages: click, tinydb, terminaltables, six, python-xlib, pynput, lockfile, setuptools, docutils, python-daemon, humanize, colored, inotify-simple, xdg, quikey
Successfully installed click-7.0 colored-1.3.93 docutils-0.15.2 humanize-0.5.1 inotify-simple-1.1.8 lockfile-0.12.2 pynput-1.4.2 python-daemon-2.2.3 python-xlib-0.25 quikey-0.1.0 setuptools-41.2.0 six-1.12.0 terminaltables-3.1.0 tinydb-3.14.1 xdg-3.0.2

APPARENT SUCCESS

ATTEMPT TO START

bdl@D54:~
$ qk start
bash: qk: command not found

START FAIL 

INSTALL FURTHER IN TERMINAL:

bdl@D54:~
$ pip3 install --user -U quikey
Collecting quikey
  Using cached https://files.pythonhosted.org/packages/6c/58/ebb25a4ffd698b0f0bf196443452ebbe5d78ac04a96d3964ebac8118144b/quikey-0.1.0-py3-none-any.whl
Collecting inotify-simple (from quikey)
Collecting tinydb (from quikey)
  Using cached https://files.pythonhosted.org/packages/dc/90/ced9f2a57513eb75dce70760e55967ceedbf2dc158b6a66f1bf87ac8fab0/tinydb-3.14.1-py2.py3-none-any.whl
Collecting python-daemon (from quikey)
  Using cached https://files.pythonhosted.org/packages/e6/44/6734382d1beb8704137ec94589e7d173a415f3396e34d020fb6b6271c2ff/python_daemon-2.2.3-py2.py3-none-any.whl
Collecting click (from quikey)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting xdg (from quikey)
  Using cached https://files.pythonhosted.org/packages/cc/7e/10b63c5d0546fc168ced3465c520b00de698d960e1c74800aea2a777aa8e/xdg-3.0.2-py2.py3-none-any.whl
Collecting terminaltables (from quikey)
Collecting pynput (from quikey)
  Using cached https://files.pythonhosted.org/packages/94/92/9e83e382f808b57330bed06855489242b77c262406aeca4960a16c8666d9/pynput-1.4.2-py2.py3-none-any.whl
Collecting colored (from quikey)
Collecting humanize (from quikey)
Collecting docutils (from python-daemon->quikey)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting lockfile>=0.10 (from python-daemon->quikey)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting setuptools (from python-daemon->quikey)
  Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl
Collecting python-xlib>=0.17; "linux" in sys_platform (from pynput->quikey)
  Using cached https://files.pythonhosted.org/packages/f7/91/9f794491d1a8b810a9d4bb8fc9766a98354cb62bd6990685032b00f87001/python_xlib-0.25-py2.py3-none-any.whl
Collecting six (from pynput->quikey)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: inotify-simple, tinydb, docutils, lockfile, setuptools, python-daemon, click, xdg, terminaltables, six, python-xlib, pynput, colored, humanize, quikey
Successfully installed click-7.0 colored-1.3.93 docutils-0.15.2 humanize-0.5.1 inotify-simple-1.1.8 lockfile-0.12.2 pynput-1.4.2 python-daemon-2.2.3 python-xlib-0.25 quikey-0.1.0 setuptools-41.2.0 six-1.12.0 terminaltables-3.1.0 tinydb-3.14.1 xdg-3.0.2
bdl@D54:~
$ pip3 show quikey | grep Version
Version: 0.1.0
bdl@D54:~
$ qk status
bash: qk: command not found
bdl@D54:~
$ git clone https://github.com/bostrt/quikey.git
Cloning into 'quikey'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 199 (delta 0), reused 2 (delta 0), pack-reused 193
Receiving objects: 100% (199/199), 34.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (123/123), done.
bdl@D54:~
$ cd quikey
bdl@D54:~/quikey
$ virtualenv v
bash: virtualenv: command not found
bdl@D54:~/quikey
$ sudo virtualenv v
sudo: virtualenv: command not found
bdl@D54:~/quikey
$ source v/bin/activate
bash: v/bin/activate: No such file or directory
bdl@D54:~/quikey
$ pip3 install --editable

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

--editable option requires 1 argument
bdl@D54:~/quikey
$ pip3 install --editable .
Obtaining file:///home/bdl/quikey
Collecting click (from quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting colored (from quikey==0.0.9)
Collecting python-daemon (from quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/e6/44/6734382d1beb8704137ec94589e7d173a415f3396e34d020fb6b6271c2ff/python_daemon-2.2.3-py2.py3-none-any.whl
Collecting inotify-simple (from quikey==0.0.9)
Collecting tinydb (from quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/dc/90/ced9f2a57513eb75dce70760e55967ceedbf2dc158b6a66f1bf87ac8fab0/tinydb-3.14.1-py2.py3-none-any.whl
Collecting pynput (from quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/94/92/9e83e382f808b57330bed06855489242b77c262406aeca4960a16c8666d9/pynput-1.4.2-py2.py3-none-any.whl
Collecting terminaltables (from quikey==0.0.9)
Collecting xdg (from quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/cc/7e/10b63c5d0546fc168ced3465c520b00de698d960e1c74800aea2a777aa8e/xdg-3.0.2-py2.py3-none-any.whl
Collecting humanize (from quikey==0.0.9)
Collecting lockfile>=0.10 (from python-daemon->quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting docutils (from python-daemon->quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting setuptools (from python-daemon->quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c893dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl
Collecting python-xlib>=0.17; "linux" in sys_platform (from pynput->quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/f7/91/9f794491d1a8b810a9d4bb8fc9766a98354cb62bd6990685032b00f87001/python_xlib-0.25-py2.py3-none-any.whl
Collecting six (from pynput->quikey==0.0.9)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: click, colored, lockfile, docutils, setuptools, python-daemon, inotify-simple, tinydb, six, python-xlib, pynput, terminaltables, xdg, humanize, quikey
  Found existing installation: quikey 0.1.0
    Uninstalling quikey-0.1.0:
      Successfully uninstalled quikey-0.1.0
  Running setup.py develop for quikey
Successfully installed click-7.0 colored-1.3.93 docutils-0.15.2 humanize-0.5.1 inotify-simple-1.1.8 lockfile-0.12.2 pynput-1.4.2 python-daemon-2.2.3 python-xlib-0.25 quikey setuptools-41.2.0 six-1.12.0 terminaltables-3.1.0 tinydb-3.14.1 xdg-3.0.2
bdl@D54:~/quikey
$ qk
bash: qk: command not found

END OF ATTEMPT

BEGIN REMOVAL OF HAIR ON HEAD

#### END OF ISSUE SUBMISSION

**Comment by bostrt** [comment]
Hello @qalisto,

Thanks for the issue submission. 

> You invested a lot of time into writing this app, yet instructions or methods for easier instruction for the growing users of Linux (abandoning Windows) is not done.

I have a plan to create some better installation docs that would help a new Linux user get going fast. This is being tracked here: https://github.com/bostrt/quikey/issues/21.

> Some of us can't build these apps. Can't compile - make - etc.
> We simply want an intriguing new app to work without having to be a senior engineer at Waymo.
> You would achieve far greater fame if you simply made this work into an installable Debian package.

I will investigate distributing the package via `.deb` and `.rpm`. For the time being, I've chosen to only release Quikey using the independent Python Package (pip). 

> A GUI would make you a cult figure.
> Text replacement is critical for serious OS users and Autokey is not user-friendly.

At this point, I do not see a GUI on the horizon but I will keep this in mind for future releases.

> What do we need to provide you to diagnose what is missing?
> Is it obvious?
> Really keen to get QK running on my MX Linux installation.
> If you could assist us pitiful newbies - be assured it would be appreciated.

Certainly! I am here to help. I see this in the failure:

```
bdl@D54:~
$ qk start
bash: qk: command not found
```

Since the installation succeeded, I believe that the default Python binary directory is not included in your `$PATH` variable. What you can do is this:

1. `pwd`
2. `pip3 show -f quikey`?
3. `echo $PATH`?

I'll be happy to take a look at those and see if there is an improvement for Quikey's installation.

NOTE: Most of my testing is done by myself and on Fedora Linux. I'm open to testing on other platforms.

**Comment by bostrt** [comment]
@qalisto following-up on my last comment, did it help you out?

**Comment by qalisto** [comment]
Robert-  Impressed with your care!  Thanks.

I did all the above with no apparent error messages by System and STILL when I try to start I get:

bdl@D54:~
$ qk start
bash: qk: command not found
bdl@D54:~
$ 

What command for what logs or file copies may I send you to help you help me isolate the problem?

I know it is probably something obvious to an experienced user.

Is this a Path variable that did not "take" or what?  Some setting that tells system where to find and execute your EXE's?

Is there a list of test commands I need to send to confirm that the necessary installations *did* take?

I have DL'd and unzipped many Apps and they run fine on Rt Click / Execute.

This install a challenge but is likely a simple absence of a PATH variable or the addition of simple lines to a key Linux .ini file.

Thanks for patience.    -Q

**Comment by qalisto** [comment]
Sorry - I see you were looking for below result .....

$ pwd
/home/bdl
bdl@D54:~
$ pip3 show -f quikey
Name: quikey
Version: 0.0.9
Summary: A keyboard macro tool.
Home-page: https://github.com/bostrt/quikey
Author: bostrt
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/bdl/quikey
Requires: click, colored, python-daemon, inotify-simple, tinydb, pynput, terminaltables, xdg, humanize
Files:
Cannot locate installed-files.txt
bdl@D54:~
$  echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin
bdl@D54:~
$ 

See a problem??

**Comment by bostrt** [comment]
Hello,

Sorry for the delay. Busy with the day job.

So it looks like Debian and its derivatives do not include `~/.local/bin` into their default `$PATH`. This means the place there Python 3 Pip installs isn't automatically configured.

To workaround this in a Debian, Ubuntu, or MX Linux installation, you can follow one of these two options:

Option 1) 
Install *without* the `--user` flag. This may require root/sudo privilege just as if you installed using `apt-get install`:
$ pip install quikey

Option 2)
Configure `~/.local/bin` in your `$PATH`:
$ echo 'PATH=$PATH:~/.local/bin' >> ~/.bashrc
$ source ~/.bashrc
$ qk 

I will be adding this to documentation within the next week.

**Comment by bostrt** [comment]
I am planning on adding quikey to a PPA repository which you would be able to use in MX Linux. I've not done this before so will take some time to setup. Releasing a PPA package should address the `$PATH` weirdness you experienced before

**Comment by bostrt** [comment]
Hi @qalisto, I will archive this issue for now since we've addressed the issue. Not that I have created #21 to address your documentation request. If you have any more questions about this issue (#23) please let me know! I hope quikey is serving you well in the meantime.
