### ISSUE TITLE
Everything works except actual macro key expansion

### ISSUE THREAD

**Issue by sdothum** [bostrt/quikey#33]
On voidlinux, everything was fine with quikey installed with python3.6. 

With python3.8, all pk commands work (add, rm, ls, start, stop, etc) -- did a pip3 install for the new python version.

Macro expansion simply backspaces over the macro name string after entering SPACE.

Curious.

**Comment by bostrt** [comment]
Thanks for the report! I'll take a look next week once I'm back to a normal schedule.

**Comment by bostrt** [comment]
@sdothum My local testing is on Python 3.6 and 3.7. I'll do some testing on 3.8 to see what's up. If you can check if there are any errors this file, it would be helpful: `~/.local/share/quikey/qkdaemon.log`

**Comment by sdothum** [comment]
The qkdaemon.log is empty. Let me know if there is anything else i can provide.

**Comment by bostrt** [comment]
I've performed a test using a python 3.8.1 container and seems to work fine. I will try in a void linux VM to see if there's something unique to their python 3.8 or _X_ distribution.

**Comment by sdothum** [comment]
i installed on an updated void machine with python 3.8 that never had quikey installed for python 3.6.

quikey works!

So my question now is.. what do i need to clean up on the machine that had quikey installed under python 3.6? 

i removed the site-packages for quikey under python 3.6 but quikey still doesn't work. Weird.

**Comment by bostrt** [comment]
> i installed on an updated void machine with python 3.8 that never had quikey installed for python 3.6.

Interesting! Thanks for testing this. I've never used Void Linux before so was struggling with some basic tasks :) 

> i will try removing all the .local python libraries and simply reinstall. i may not have time to do this for awhile as i will be travelling with the laptop i just installed it on and is working :-)

Yes, at this point, I would only be able to guess a reinstall. There could certainly be a mismatch of 3.6 vs 3.8 libraries installed. I'll try a little more to get a Void Linux environment setup to test further. I'll make sure to install python3.6 first, install quikey, and then upgrade to python3.8 since that seems to be the reproducer.

**Comment by sdothum** [comment]
Removing the .local python libraries and reinstalling did the trick. I also removed the bin/__pycache__. Quite possibly just removing the __pycache__ may have been all that was needed.

**Comment by bostrt** [comment]
Thanks for following up on this @sdothum. If this happens again, please feel free to reopen this issue.
