### ISSUE TITLE
Add shortcuts to disable

### ISSUE THREAD

**Issue by Oreolek** [bostrt/quikey#41]
Suppose you add a macro for `q` and `k` keys, how to stop `qk` without using the console?

**Comment by bostrt** [comment]
A GUI for stopping and starting quikey will be considered in much later versions. For now, it will only have command line tool management. Note that you consider creating key bindings in your desktop environment (GNOME and KDE support this if you use them), that execute the `qk start` and `qk stop` commands as you need them.

Note that if you are experiencing an issue with quikey not starting at login, this will be addressed in the next release.
