### ISSUE TITLE
Question - Can quikey simulate pressing the enter key?

### ISSUE THREAD

**Issue by xircon** [bostrt/quikey#45]
Not a biggy, but can be useful.

**Comment by bostrt** [comment]
@xircon Yep! If you create a phrase that is multi-line then each new line will result in an enter key press. Here's a not-very-graceful example:

https://asciinema.org/a/ZPkMbGwVpyYPmgG0RtLccjyTs

Let me know if that doesn't work the way you'd expect or you had a different use-case in mind.

**Comment by xircon** [comment]
Hadn't thought of that, closing.

**Comment by bostrt** [comment]
No prob! Happy to help :)
