### ISSUE TITLE
Adding linefeed in interactive edit not working.

### ISSUE THREAD

**Issue by xircon** [bostrt/quikey#48]
Using micro editor, I set up a phrase:
```
qk -n 'updg'
```
#### Enter the phrase, press enter:
![image](https://user-images.githubusercontent.com/1316691/100499617-e694ce80-3162-11eb-9fc4-f430909eb0b0.png)

#### Phrase after expansion:
![image](https://user-images.githubusercontent.com/1316691/100499748-147a1300-3163-11eb-9d68-f0a625feb4d2.png)

Also qk daemon seems to not work after an interactive edit and I have to restart:
```
qk stop && qk start
```
Then all is good.

If I manually edit the json and add '\n' it works.

**Comment by bostrt** [comment]
Hi! Thanks for reporting this. I'm seeing this issue in my side too and
will investigate a fix soon.

**Comment by xircon** [comment]
Thanks.

**Comment by bostrt** [comment]
I'm reworking the edit screen a bit to address the issue you found with newlines. 

Regarding the quikey-daemon failure, here's the stacktrace when editing a phrase as you stated. I'll address this as well. 

```
$ quikey-daemon start -f
/home/rbost/.cache/quikey/quikey.pid
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/rbost/.local/lib/python3.7/site-packages/quikey/filewatch.py", line 24, in run
    observer.notify()
  File "/home/rbost/.local/lib/python3.7/site-packages/quikey/qkdaemon.py", line 31, in notify
    self.init_phrase_handlers()
  File "/home/rbost/.local/lib/python3.7/site-packages/quikey/qkdaemon.py", line 25, in init_phrase_handlers
    phrases = self.db.all()
  File "/home/rbost/.local/lib/python3.7/site-packages/quikey/models.py", line 33, in all
    return self.db.all()
  File "/home/rbost/.local/lib/python3.7/site-packages/tinydb/database.py", line 426, in all
    return list(itervalues(self._read()))
  File "/home/rbost/.local/lib/python3.7/site-packages/tinydb/database.py", line 399, in _read
    return self._storage.read()
  File "/home/rbost/.local/lib/python3.7/site-packages/tinydb/database.py", line 90, in read
    raw_data = self._storage.read() or {}
  File "/home/rbost/.local/lib/python3.7/site-packages/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/usr/lib64/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 9318 (char 9317)
```

**Comment by bostrt** [comment]
The quikey-daemon issue has been a troubleshooting challenge, but using inotify CLI tools, I see the phrase database is invalid for a very short period of time. I'll have to dig into why this is the case next.

```
$ inotifywait -e modify $WATCHFILE && cat $WATCHFILE
Setting up watches.
Watches established.
/home/rbost/.local/share/quikey/phrases.json MODIFY 
{"_default": {"1": {"key": ":test:", "value": "testing", "tags": [], "updated": "2020-11-29T02:27:35.160585"}}}}}
```

*Note the extra `}` at the end*

**Comment by xircon** [comment]
May be a lack of coffee, but I can see 2 extra closing braces?

**Comment by bostrt** [comment]
Yep, you are right. I'm trying to figure out if that's something I
introduced in quikey or coming from an underlying library.

**Comment by bostrt** [comment]
Looks like its due to tinydb not supporting multi-threading/processing. Fortunately, quikey edits do not require high performance so I can introduce a file lock to address this. I'll start work on this soon and have a goal to get a new release out this week. 

Reference:
https://github.com/msiemens/tinydb/issues/215

**Comment by xircon** [comment]
Anything I can do, let me know.

**Comment by xircon** [comment]
Quick test, all seems to be working, needs python-filelock adding to the aur packages depends.

**Comment by bostrt** [comment]
Yep! I'll leave that to @SanskritFritz to sort out in the aur release.

**Comment by SanskritFritz** [comment]
I don't have python-filelock installed on my archlinux, but qk seems to work well here. Why is that dependency needed?

Don't get me wrong, I'm willing to add it, just want to clarify this.

**Comment by SanskritFritz** [comment]
Ah, OK, it's a new dependency, now I see. So it will be included in the next release, however, the -git package will be updated soon.

**Comment by bostrt** [comment]
It was added as part of some locking needed to address a race condition in
accessing the quikey database. I made sure to check the dependency was
available in Arch repos before adding. Hope I confirmed that correctly!

**Comment by bostrt** [comment]
Thanks!! :)

**Comment by xircon** [comment]
Thank you both!

**Comment by SanskritFritz** [comment]
OK, AUR packages updated, thanks guys. This stuff is getting better and better.
