### ISSUE TITLE
Update to pynput today breaks quikey (ArchLinux)

### ISSUE THREAD

**Issue by xircon** [bostrt/quikey#52]
Just a heads up, downgrading:
```
warning: downgrading package python-pynput (1.7.3-1 => 1.7.2-1)
```
Fixes,

**Comment by bostrt** [comment]
Hi @xircon, thanks for the heads up! I just updated pynput on my side and quikey seems to be functioning okay. What exactly was breaking for you?

**Comment by xircon** [comment]
Looks like the package has been fixed!! Current version is:
```
aur/python-pynput 1.7.3-2 [installed] 
```
As noted above 1.7.3-1 did not work, updated, all good.

**Comment by bostrt** [comment]
Oh I see :) many thanks for the report anyways!
